name: Docker Image CI

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/jamesread/prometheus-exporter-github-micro:${{ github.ref_name }}

    - name: Push the docker image
      run: docker push ghcr.io/jamesread/prometheus-exporter-github-micro:${{ github.ref_name }}

    - name: Tag the docker image
      run: docker tag ghcr.io/jamesread/prometheus-exporter-github-micro:${{ github.ref_name }} ghcr.io/jamesread/prometheus-exporter-github-micro:latest

    - name: Push the docker image
      run: docker push ghcr.io/jamesread/prometheus-exporter-github-micro:latest

